### How CNNs, CDRs, and ArcGIS Will Revolutionize Poverty and Food Insecurity in Rwanda

## Introduction

	This literature review deals with the subject of poverty and food insecurity in Rwanda, and how evidently interconnected these two aspects of human development are. One of the biggest obstacles plaguing the nation today, and much of Eastern Africa, is a lack of reliable, consistent, and easily accessible information about spatial data and census counts. In an effort to combat this, and develop useful geospatial data that can be utilized as an effective way to distribute humanitarian aid, multiple studies have been conducted to propose new data science methods of tackling these issues. Some of the most prominent ones that will be discussed further are using GIS to analyse household indicators of poverty, deep learning models, and call detail records, to touch on a few. In combination with this, survey data, particularly of hospitals and households, has shown to provide essential details in the fight against food insecurity and widespread poverty in Rwanda. 

## Human Development Topic 

	When beginning to research the effects of food insecurity, and consequently malnutrition in Rwanda, it became quickly evident that this topic is inherently linked to the unusually high poverty rate in Rwanda, and thus, these two concepts must be viewed through the same lens. Rwanda is the most densely populated nation in all of Africa, and with more refugees pouring into the country yearly, the completely agricultural society is struggling to maintain an adequate amount of resources to support everyone. With a population density of 1,360 people per square mile, the mortality rate as a result of poverty has skyrocketed, particularly among children, and the average life expectancy does not exceed 50 years.  The significance of these harms is that as the economy is agriculturally-based, the means of living has been based upon the growth of crops, which has proven to be detrimental, particularly as climate patterns become increasingly unpredictable. Thus, food sources have been unreliable nationwide. Analyzing this dimension of human development draws a parallel to Amartya Sen’s definition of freedom, which defines human development as the expansion of the freedoms and opportunities that citizens have in all areas of life, whether that is political, economic, or, in this case, freedom from poverty. Having such limited resources and being subjected to a life of poverty creates a sort of metaphorical trap, where opportunities are not able to be pursued as most if not all members of the family must work tirelessly to provide the most basic necessities for their family, which are still not guaranteed at the end of the say. Facing the issue of poverty and food insecurity head-on in Rwanda is the first step towards true development in this developing country, and grants the citizens of Rwanda a small piece of freedom in and of itself. When looking at the SDGs that this research relates to, the goals that most closely align to this topic are numbers one and two, which are to end poverty and end hunger, respectively. SDG #1 focuses on the necessity for stable jobs and economic equality, while SDG #2 centers more around how the agricultural sector can grow, both aligning with the prominent issues in Rwanda. 

## Human Development Process

	When analyzing food insecurity in Rwanda, one of the key aspects that must be looked at is the agricultural state of the country and how certain models can predict agricultural productivity and crop potential. In the article published by Muhire, the model developed was used in order to predict crop yields as well as future climate patterns, such as changes in precipitation. Annual variability in rainfall can account for up to 30% of crop yield fluctuations on a global scale, but when looking solely at Rwanda, which has a much smaller crop input and bases agricultural growth solely on rain, climate changes can account for up to 80% of the variability in annual crop yields. Furthermore, aridity is even more common in Rwanda since the nation already has a decreased water supply. Thus, what Muhire did was develop a model that utilized climate data from 2000-2010 as well as a stochastic weather generator from the Rwandan Meteorological Center which calculated the average temperature and precipitation for the years 2000-2050 in order to predict the future crop yields for 2011-2050. In addition, this data could be implemented to see how suitable certain major crops would be for growth in the future. [7] In addition to this, Benimana’s study focused on using a spatial water balance technique which was used to analyze the potential for harvesting rainwater to use when producing crops, and thus forming plans to increase food security in the Bugesera District, a very arid and drought-prone part of Rwanda. They determined the amount of water runoff (a proxy for rainwater), which could then be collected, by using the Natural Resources Conservation Service Curve Number method. [5] 
Another core aspect apart from the agriculture side of food insecurity and poverty in Rwanda is using what Akinyemi calls Economic Development and Poverty Reduction Strategies (EDPRS). By using GIS-based images of poverty, indicators of poverty (education status, etc.) visualized cartographically can be used in combination with geographic information in order to find the sources of poverty and target them directly. [2] In another one of Akinyemi’s studies, titled “A Conceptual Poverty Mapping Data Model”, she mentions the fact that while GIS is increasingly being used in poverty mapping, there is no generic database model for the development of databases. She argues that while there are already industry-specific models, having a generic one would make the incorporation of spatial data in assessments of poverty far less complex. The underlying goal would be for a level of standardization to arise for the most commonly used data types, which would allow the sharing of spatial data between multiple poverty aid efforts. [1]
One of the most fascinating approaches to predicting poverty is detailed in the study written by Jean, where the key concept is using satellite images in order to compare landscape features with economic data. The proposed process is to use a transfer learning model, which would start with a convolutional neural network (CNN) model that was trained on ImageNet. From there, the CNN would be able to perform nonlinear mapping from each input image to a precise vector representation. [6] Another significant spatial data source are CDRs, which are used in Njuguna’ study on big data. Njuguna emphasizes the cost and labor efficiency of CDRs, and proposes to utilize features that are representative of socioeconomic status as proxies, which are then statistically analyzed and aggregated at the sector level to match the spatial resolution of the true value, or, the MPI. Though this does focus primarily on a statistical analysis, using the Least Absolute Shrinkage and Selection Operator (LASSO) or ridge regression prior to the final model, the efficiency of such a model should be recognized in the context of Rwanda’s human development progress. [9]


## Geospatial Data Science Methods

	The resulting data when looking at the various proposed spatial models each showed their own slightly unique take on how to best deal with this specific aspect of human development. On the agricultural front, Muhire’s study revealed that the future precipitation is likely to fluctuate more than temperatures will, which will remain relatively stagnant with the exception of temperatures in areas of high altitudes. Thus, carefully analyzing what those future rainfall patterns will be is essential in understanding which crops should be produced, as a way of maximizing food intake in order to decrease food insecurity. [7] In Benimana’s study, the dataset used was land cover data that was obtained from digital LANDSAT images, and the results found that the average runoff daily was 880 x 106 m3. To put this into perspective, utilizing this excess water could produce up to 531 x 103 tons of paddy rice and 1,620 x 103 tons of corn, which is an extreme difference in such an agriculturally-based economy, where maximizing crop yields in this way could revolutionize the standard of living. [5]
	When reviewing Akinyemi’s GIS-based approach, her study utilized the ArcGIS 9.3 software package to map the data for this study and to integrate all spatial data obtained into vector formats, the household living standards analyzed being household health, education, and accessibility to services. These indicators of poverty are then able to be used to map their frequency and distribute aid where it is most necessary. [2] In her other idea of developing a standard, generic model for poverty mapping, she touches on the key thematic layers of what data that model would need to have. This includes administrative and census boundaries, environmental factors, transportation pathways, geographical names, infrastructure, and lastly, land boundaries. In said model, data would be aggregated to aid the management of geographical activities, so an entity could be represented in multiple corresponding spatial entities. For example, a city in a small-scale database could be a point, and the same city could also be a polygon in a large-scale database. [1]
	With the transfer learning model, the results yielded by the CNN revealed that this model was able to extremely accurately predict average household consumption and wealth across multiple African countries, which would allow aid efforts to be implemented where they are needed most. [6] In a different approach, Stöcker focuses on a different tool for acquiring land tenure data: Unmanned Aerial Systems (UAS). Thus, a socio-technical study was conducted in Rwanda and aimed to evaluate the workflow of UAS and the final products of valuable spatial data to be used for land administration and spatial planning. Three UAS were flown to examine the quality of the data and how this technology would work in the current institutional environment. The results were that UAS can contribute to match the prioritized needs in Rwanda but the current capacity conditions do not have the sufficient potential. [10]
	Another core aspect of data science methods is survey data. In the study of dietary diversity scores among children, hospitals conducted surveys in order to determine what the children had eaten in the past day, which revealed an overwhelming lack of diversity in food groups. The results were grouped by age, and revealed that the median dietary diversity score for children between the ages of 6-12 months was a 2 out of the possible 7 and for children between 13-23 months old, this score rose to 4, the minimum dietary diversity score, just further showing the reality of food insecurity in Rwanda. [8] Habyarimana also conducted a survey-based study, where household survey data was collected in order to reveal significant indicators of poverty. The results were that the age of the household head, education level of the household head, gender of the household head, place of residence, the province of household head and size of the household (number of household members) were the most significant predictors of poverty in Rwanda. [4]
	Lastly, it is important to mention Akinyemi’s assessment of how spatial data is currently shared in Rwanda. She first emphasizes the importance of accessible geographic information, and how it transforms the economy and the effectiveness of businesses in the private sector, increasing citizen’s involvement in governance. An assessment of data sharing was conducted in Rwanda, where organizations that produced or used spatial datasets were surveyed. The results were that the dominant shared datasets were administrative boundaries and topographic maps, where most spatial data was exchanged through printed maps. Additionally, those using and producing data in Rwanda believe the key to data sharing in Rwanda is that there must be a national policy on the access and sharing of data. [3]


## Discussion

	Overall, there are many proposed data methods for how to revolutionize human development in Rwanda, in particular how to address the significant issues of poverty and food insecurity. My progress thus far has been narrowing down the most promising and well-supported data science models, and as I continue I hope to narrow it down even further to compare the models, such as the benefits of ArcGIS analysis versus a transfer learning model. I do believe a gap in the literature exists, as Akinyemi mentioned that there is still very limited public access to a majority of spatial information. Making more of this information publicly accessible is how I believe that the gap will be closed and even more models can be proposed to find a solution for Rwanda’s struggles with food insecurity and poverty.

## References

Akinyemi, F. (2010). A conceptual poverty mapping data model. Transactions in GIS, 14, 85-100. doi:10.1111/j.1467-9671.2010.01207.x
Akinyemi, F., & Bigirimana, F. (2012). A spatial analysis of poverty in KIGALI, Rwanda using indicators of household living standard. KIST Journal of Science and Technology.
Akinyemi, F., & Uwayezu, E. (2011). An Assessment of the Current State of Spatial Data Sharing in Rwanda. International Journal of Spatial Data Infrastructures Research, 6, 365-387.
Habyarimana, Zewotir, & Ramroop. (2015). Analysis of demographic and health survey to measure poverty of household in Rwanda. African Population Studies, 29.
J, C. B., U, G. W., I, N., F, O. K., & W, G. (2015). Rainwater harvesting potential for crop production in the BUGESERA District of Rwanda. African Journal of Agricultural Research, 10(19), 2020-2031. doi:10.5897/ajar12.820
Jean, N., Burke, M., Xie, M., Davis, W. M., Lobell, D. B., & Ermon, S. (2016). Combining satellite imagery and machine learning to predict poverty. Science. doi:10.1126/science.aaf7894
Muhire, I., Ahmed, F., Abutaleb, K., & Kabera, G. (2015). Impacts of projected changes and variability in climatic data on major food crops yields in Rwanda. International Journal of Plant Production.
N., D., K.V., R., J., M., & Sharma, A. (2018). The study of dietary diversity score in children between 6 months to 23 months: A hospital based study. International Journal of Contemporary Pediatrics. http://dx.doi.org/10.18203/2349-3291.ijcp20181541
Njuguna, C., & McSharry, P. (2017). Constructing spatiotemporal poverty indices from big data. Journal of Business Research. doi:https://doi.org/10.1016/j.jbusres.2016.08.005
Stöcker, C., Ho, S., Nkerabigwi, P., Schmidt, C., Koeva, M., Bennett, R., & Zevenbergen, J. (2019). Unmanned aerial System Imagery, land data and user needs: A Socio-Technical assessment in Rwanda. Remote Sensing, 11(9), 1035. doi:10.3390/rs11091035

